
services:
    demo-arches-c09fc:
      container_name: demo-arches-c09fc
      image: he/demo_arches-c09fc:dev_build
      build:
        args:
          - "PROJ_NAME=demo_arches"
          - "PROJ_REPO_NAME=demo-arches"
          - "DOCKER_PATH=./.arches_containers/demo_arches/docker"
        context: ../..
        dockerfile: ./.arches_containers/demo_arches/Dockerfile
        target: dev
      command: run_arches
      volumes:
        - ../../arches:/web_root/arches
        - ../../demo-arches:/web_root/demo_arches
        - ./docker:/web_root/docker
        - ../../demo-arches-package:/web_root/demo_arches_package
        - ../../demo-arches-data:/web_root/demo_arches_data
      env_file:
        - ./docker/env_file.env
      ports:
        - 8002:8000
        - 5678:5678
      stdin_open: true
      tty: true
    
    demo-arches-c09fc-livereload:
      profiles:
        - livereload
      container_name: demo-arches-c09fc-livereload
      image: he/demo_arches-c09fc:dev_build
      command: run_livereload
      volumes:
        - ../../arches:/web_root/arches
        - ../../demo-arches:/web_root/demo_arches
      env_file:
        - ./docker/env_file.env
      ports:
        - 35729:35729      
      depends_on:
          - demo-arches-c09fc
      stdin_open: true
      tty: true
    
    demo-arches-c09fc-webpack:
      container_name: demo-arches-c09fc-webpack
      image: he/demo_arches-c09fc:dev_build
      command: run_webpack
      volumes:
        - ../../arches:/web_root/arches
        - ../../demo-arches:/web_root/demo_arches
      env_file:
        - ./docker/env_file.env
      ports:
        - 8028:8021
      depends_on:
          - demo-arches-c09fc
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: demo-arches-c09fc-network

volumes:
    arches-log-c09fc:
    arches-static-c09fc:
