server {

  location /featureserver/ {
    proxy_pass http://pg-feat-demo-arches:9000/;
  }

  location /tileserver/ {
    proxy_pass http://pg-tile-demo-arches:7800/tileserver/;
  }

  location / {
    proxy_pass http://demo-arches:8000/;
  }

}