services:
  demo-dagster:
    container_name: demo-dagster
    image: he/dagster:dev
    build:
      args:
        PROJ_NAME: demo_dagster
        PROJ_REPO_NAME: demo-dagster
      context: ../..
      dockerfile: ./.dagster_containers/demo_dagster/Dockerfile
      target: dev
    env_file: 
      - ./docker/env_file.env
    volumes:
     - ..:/workspaces/demo-dagster-arches:cached
     - dagster-data:/opt/dagster/dagster_home
    ports:
      - 3000:3000
      - 5679:5679

networks:
  default:
    external: true
    name: demo-dagster-network

volumes:
  dagster-data:
